name: Build and Deploy Docs

on:
  push:
    branches: [ "main" ]  # or your default branch
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Lock File
        run: wget -q https://raw.githubusercontent.com/atharva-2001/tardis/refs/heads/logger_widget_panel/conda-linux-64.lock
        shell: bash
      
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-linux-64.lock
          environment-name: tardis
          
      # - name: Install additional dependencies
      #   shell: micromamba-shell {0}
      #   run: |
      #     pip install sphinx sphinx_rtd_theme  # add any other doc dependencies here

      - name: Build documentation
        shell: micromamba-shell {0}
        run: |
          sphinx-build -M html source build
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/html'  # replace with your build output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # only deploy on main branch
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
